[package]
name = "BugCreator"
authors = ["Roblox"]
license = "Proprietary"
content_root = "src"
version = "1.0.0"
files = ["*", "!**.story.lua"]

[dependencies]
AssessmentCore = "github.com/imbellus2/assessment-core@7.0.18"
AssessmentUI = "github.com/imbellus2/assessment-ui@3.0.0"
FishBlox = "github.com/imbellus2/fishblox@6.0.32"
Dash = "github.com/roblox/dash@0.1.7"
Roact = { target = "github.com/roblox/roact-alignment", version = "17.0.1-rc.11", package = "RoactCompat" }
React = "github.com/roblox/roact-alignment@17.0.1-rc.11"
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.11"
Rodux = "github.com/Roblox/rodux@3.0.0"
RoactRodux = "github.com/Roblox/roact-rodux@0.5.0"
Utilities = "github.com/imbellus2/assessment-utils@3.0.5"

[dev_dependencies]
TestEZ = "github.com/roblox/testez@0.4.1"
Rockuna = "github.com/imbellus2/rockuna@1.0.0"
TestUtils = "github.com/imbellus2/assessment-test@1.0.4"
Storybook = "github.com/roblox/storybook-lib@1.0.0"

# Roact 17 - Patch in flagged proxy for roact
[config.patch."github.com/roblox/roact"]
Roact = { target = "github.com/roblox/roact-alignment", version = "17.0.1-rc.11", package = "RoactCompat" }